image: docker:latest

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  MISTBORN_DEFAULT_PASSWORD: "default_password"
  MISTBORN_DNS_BIND_IP: "10.2.3.1"
  
stages:
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

docker_build:
  stage: test
  script:
    - apk add docker-compose
    - bash scripts/subinstallers/gen_prod_env.sh "$MISTBORN_DEFAULT_PASSWORD"
    - docker-compose -f base.yml build

